Landing Page
proyectosolidus/ProyectoSolidus pull request #12
Opened 2021-02-09 14:32 UTC by gasparnd

Landing Page made whit React

2021-02-10 08:05 UTC, jroji requested changes
Está genial! muchas gracias por el aporte :D

2021-02-10 08:05 UTC, jroji commented on public/index.html
> +    <meta
Actualizar metas a algo más relacionado con el proyecto, no hace falta nada complejo 😊

2021-02-10 08:05 UTC, jroji commented on public/manifest.json
> +  "short_name": "React App",
Actualizar nombre e información de la web.

@jmlweb algo sobre logos para el icono de la PWA?

2021-02-10 08:05 UTC, jroji commented on src/components/ContactForm.js
> +					Cuéntanos sobre tu organización y nosotros <span>te ayudaremos gratis</span> <br/>
cambiar nosotros por "desde Solidus" y "los integrantes" por "el equipo"

2021-02-10 08:06 UTC, jroji commented
> Successfully deployed to the following URLs:
> 
> * [proyecto-solidus.gasparnd.vercel.app](https://proyecto-solidus.gasparnd.vercel.app)
> * [proyecto-solidus.vercel.app](https://proyecto-solidus.vercel.app)
> * [proyecto-solidus-git-main.gasparnd.vercel.app](https://proyecto-solidus-git-main.gasparnd.vercel.app)

Habría que revisar esto @jmlweb

2021-02-12 10:39 UTC, gasparnd commented on src/components/ContactForm.js
> +					Cuéntanos sobre tu organización y nosotros <span>te ayudaremos gratis</span> <br/>
Ok, ahora mismo estoy haciendo otros pequeños cambios, con el feedback que me dieron

2021-02-12 14:42 UTC, closed without merging